replica: 1
image:
  repo: docker9119/encrpt-decrypt-app
  tag: latest
healthcheck: 
  url: /api/health
name: encrpt-decrypt-app
containerPort: 5000
service:
  name: encrpt-decrypt-app
  type: ClusterIP
  port: 5000
  targetPort: 5000
